### ISSUE TITLE
hpcviewer and hpcprof should support new visibility type

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#67]
Right now, we have 
0 hide
1 show
2 exclusive only
3 inclusive only

We should add an invisible type, which is different from hide. Hide means show the metric in hpcviewer and you can adjust the visibility to your liking. invisible means "don't allow hpcviewer to adjust visibility", like empty. It would be even better if hpcviewer simply hid (in the metrics pane and in the column chooser pane) these metrics.

for example, the "accumulator" metrics for computing thread registers should not be visible anywhere!

**Comment by laksono** [comment]
Fixed in commit 15c269efcf9ae2bc2f6fa398e91e504081999944
Invisible metrics are
- not shown in metric column
- not shown in metric properties dialog
- not shown in metric hide/show dialog

But they are still shown in the graph menu because there is no correlation between metric-db and metric (still to-do).
