### ISSUE TITLE
hpcviewer ran out of memory on ppc64le while parsing an experiment.xml file

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#87]
johnmc will provide some summary details about using hpcviewer on an adagio db  at sandia on ppc64le. hpcviewer runs out of memory, despite being on a large memory node and having ulimits set high.

on x86_64, it works fine.

**Comment by laksono** [comment]
I have looked at the memory issue, and there are some possibilities:
- Eclipse compatibility layer which causes the memory problem
- ppcle64 memory is not as big as x86_64, and hpcviewer is not memory efficient.
My guess is the way we store metrics is not efficient (using dense matrix instead of sparse).

**Comment by laksono** [comment]
VisualVM shows that hpcviewer spend 25% of the total memory for storing metrics. The database is from DCA++ database. 

![image](https://user-images.githubusercontent.com/8781032/83711210-3a758f00-a5e8-11ea-8798-b65d15a9c9be.png)

**Comment by jmellorcrummey** [comment]
I will see if I can get visualvm running on ppc64le.

**Comment by jmellorcrummey** [comment]
the 2020.05 beta release works with adagio.
